package kysely.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kysely.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.11.21 21:20:31 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KoehenkiloTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi84 */
  @Test
  public void testRekisteroi84() {    // Koehenkilo: 84
    Koehenkilo p01 = new Koehenkilo(); 
    assertEquals("From: Koehenkilo line: 86", 0, p01.getKoehenkiloNro()); 
    p01.rekisteroi(); 
    Koehenkilo p02 = new Koehenkilo(); 
    p02.rekisteroi(); 
    int n1 = p01.getKoehenkiloNro(); 
    int n2 = p02.getKoehenkiloNro(); 
    assertEquals("From: Koehenkilo line: 92", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString136 */
  @Test
  public void testToString136() {    // Koehenkilo: 136
    Koehenkilo koehenkilo = new Koehenkilo(); 
    koehenkilo.parse("1|k100|f|15-21"); 
    assertEquals("From: Koehenkilo line: 139", true, koehenkilo.toString().startsWith("1|k100|f|15-21")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse159 */
  @Test
  public void testParse159() {    // Koehenkilo: 159
    Koehenkilo koehenkilo = new Koehenkilo(); 
    koehenkilo.parse("3|k100|f|15-21"); 
    assertEquals("From: Koehenkilo line: 162", 3, koehenkilo.getKoehenkiloNro()); 
    assertEquals("From: Koehenkilo line: 163", true, koehenkilo.toString().startsWith("3|k100|f|15-21")); 
    koehenkilo.rekisteroi(); 
    int n = koehenkilo.getKoehenkiloNro(); 
    koehenkilo.parse(""+(n+20)); 
    koehenkilo.rekisteroi(); 
    assertEquals("From: Koehenkilo line: 169", n+20+1, koehenkilo.getKoehenkiloNro()); 
  } // Generated by ComTest END
}