package kysely.test;
// Generated by ComTest BEGIN
import java.io.*;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
import kysely.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.07.22 14:32:58 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KoehenkilotTest {

  // Generated by ComTest BEGIN  // Koehenkilot: 41

  private Koehenkilot koehenkilot; 
  private String tiedNimi; 
  private File ftied; 

  @Before
  public void alusta() throws TallennaException {
     tiedNimi = "testikysely"; 
     ftied = new File(tiedNimi+".db"); 
     ftied.delete(); 
     koehenkilot = new Koehenkilot(tiedNimi); 
  }

  @After
  public void siivoa() {
     ftied.delete(); 
  }
  // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testEtsi133 
   * @throws TallennaException when error
   */
  @Test
  public void testEtsi133() throws TallennaException {    // Koehenkilot: 133
    Koehenkilo aku1 = new Koehenkilo(); aku1.taytaEsimTiedot(); 
    Koehenkilo aku2 = new Koehenkilo(); aku2.taytaEsimTiedot(); 
    koehenkilot.lisaa(aku1); 
    koehenkilot.lisaa(aku2); 
    try {
    koehenkilot.lisaa(aku2); 
    fail("Koehenkilot: 139 Did not throw TallennaException");
    } catch(TallennaException _e_){ _e_.getMessage(); } // ei samaa id:tä uudelleen!
    Collection<Koehenkilo> loytyneet = koehenkilot.etsi(aku1.getNimi(), 1); 
    assertEquals("From: Koehenkilot line: 141", 1, loytyneet.size()); 
    assertEquals("From: Koehenkilot line: 142", aku1, loytyneet.iterator().next()); 
    loytyneet = koehenkilot.etsi(aku2.getNimi(), 1); 
    assertEquals("From: Koehenkilot line: 144", 1, loytyneet.size()); 
    assertEquals("From: Koehenkilot line: 145", aku2, loytyneet.iterator().next()); 
    try {
    loytyneet = koehenkilot.etsi("", 15); 
    fail("Koehenkilot: 146 Did not throw TallennaException");
    } catch(TallennaException _e_){ _e_.getMessage(); }
    ftied.delete(); 
  } // Generated by ComTest END
}