package kysely.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kysely.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.10.21 20:43:03 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KoehenkiloTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi58 */
  @Test
  public void testRekisteroi58() {    // Koehenkilo: 58
    Koehenkilo p01 = new Koehenkilo(); 
    assertEquals("From: Koehenkilo line: 60", 0, p01.getKoehenkiloNro()); 
    p01.rekisteroi(); 
    Koehenkilo p02 = new Koehenkilo(); 
    p02.rekisteroi(); 
    int n1 = p01.getKoehenkiloNro(); 
    int n2 = p02.getKoehenkiloNro(); 
    assertEquals("From: Koehenkilo line: 66", n2-1, n1); 
  } // Generated by ComTest END
}