package kysely.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kysely.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.07.22 15:00:04 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KoehenkiloTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi186 */
  @Test
  public void testRekisteroi186() {    // Koehenkilo: 186
    Koehenkilo p01 = new Koehenkilo(); 
    assertEquals("From: Koehenkilo line: 188", 0, p01.getKoehenkiloNro()); 
    p01.rekisteroi(); 
    Koehenkilo p02 = new Koehenkilo(); 
    p02.rekisteroi(); 
    int n1 = p01.getKoehenkiloNro(); 
    int n2 = p02.getKoehenkiloNro(); 
    assertEquals("From: Koehenkilo line: 194", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString299 */
  @Test
  public void testToString299() {    // Koehenkilo: 299
    Koehenkilo koehenkilo = new Koehenkilo(); 
    koehenkilo.parse("1|k100|f|15-21"); 
    assertEquals("From: Koehenkilo line: 302", true, koehenkilo.toString().startsWith("1|k100|f|15-21")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse322 */
  @Test
  public void testParse322() {    // Koehenkilo: 322
    Koehenkilo koehenkilo = new Koehenkilo(); 
    koehenkilo.parse("3|k100|f|15-21"); 
    assertEquals("From: Koehenkilo line: 325", 3, koehenkilo.getKoehenkiloNro()); 
    assertEquals("From: Koehenkilo line: 326", true, koehenkilo.toString().startsWith("3|k100|f|15-21")); 
    koehenkilo.rekisteroi(); 
    int n = koehenkilo.getKoehenkiloNro(); 
    koehenkilo.parse(""+(n+20)); 
    koehenkilo.rekisteroi(); 
    assertEquals("From: Koehenkilo line: 332", n+20+1, koehenkilo.getKoehenkiloNro()); 
  } // Generated by ComTest END
}