package kysely.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import java.util.*;
import kysely.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.11.03 13:35:43 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KyselyTest {



  // Generated by ComTest BEGIN
  /** testAnnaKysymykset63 */
  @Test
  public void testAnnaKysymykset63() {    // Kysely: 63
    Kysely kysely = new Kysely(); 
    Koehenkilo k01 = new Koehenkilo(); Koehenkilo k02 = new Koehenkilo(); 
    Koehenkilo k03 = new Koehenkilo(); 
    k01.rekisteroi(); k02.rekisteroi(); k03.rekisteroi(); 
    int id1 = k01.getKoehenkiloNro(); int id2 = k02.getKoehenkiloNro(); 
    Kysymys kys1 = new Kysymys(id1); kysely.lisaa(kys1); 
    Kysymys kys2 = new Kysymys(id2); kysely.lisaa(kys2); 
    List<Kysymys> loydetyt; 
    loydetyt = kysely.annaKysymykset(k03); 
    assertEquals("From: Kysely line: 78", 0, loydetyt.size()); 
    loydetyt = kysely.annaKysymykset(k01); 
    assertEquals("From: Kysely line: 80", 1, loydetyt.size()); 
    assertEquals("From: Kysely line: 81", true, loydetyt.get(0) == kys1); 
  } // Generated by ComTest END
}