package kysely.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import java.util.*;
import kysely.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.12.14 21:06:41 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KyselyTest {



  // Generated by ComTest BEGIN
  /** 
   * testAnnaKysymykset72 
   * @throws TallennaException when error
   */
  @Test
  public void testAnnaKysymykset72() throws TallennaException {    // Kysely: 72
    Kysely kysely = new Kysely(); 
    Koehenkilo k01 = new Koehenkilo(); Koehenkilo k02 = new Koehenkilo(); 
    Koehenkilo k03 = new Koehenkilo(); 
    k01.rekisteroi(); k02.rekisteroi(); k03.rekisteroi(); 
    int id1 = k01.getKoehenkiloNro(); int id2 = k02.getKoehenkiloNro(); 
    Kysymys kys1 = new Kysymys(id1); kysely.lisaa(kys1); 
    Kysymys kys2 = new Kysymys(id2); kysely.lisaa(kys2); 
    List<Kysymys> loydetyt; 
    loydetyt = kysely.annaKysymykset(k03); 
    assertEquals("From: Kysely line: 88", 0, loydetyt.size()); 
    loydetyt = kysely.annaKysymykset(k01); 
    assertEquals("From: Kysely line: 90", 1, loydetyt.size()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testAnnaVastaukset103 
   * @throws TallennaException when error
   */
  @Test
  public void testAnnaVastaukset103() throws TallennaException {    // Kysely: 103
    Kysely kysely = new Kysely(); 
    Koehenkilo k01 = new Koehenkilo(); Koehenkilo k02 = new Koehenkilo(); 
    Koehenkilo k03 = new Koehenkilo(); 
    k01.rekisteroi(); k02.rekisteroi(); k03.rekisteroi(); 
    int id1 = k01.getKoehenkiloNro(); int id2 = k02.getKoehenkiloNro(); 
    Vastaus vas1 = new Vastaus(id1); kysely.lisaa(vas1); 
    Vastaus vas2 = new Vastaus(id2); kysely.lisaa(vas2); 
    List<Vastaus> loydetyt; 
    loydetyt = kysely.annaVastaukset(k03); 
    assertEquals("From: Kysely line: 119", 0, loydetyt.size()); 
    loydetyt = kysely.annaVastaukset(k01); 
    assertEquals("From: Kysely line: 121", 1, loydetyt.size()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testEtsi239 
   * @throws CloneNotSupportedException when error
   * @throws TallennaException when error
   */
  @Test
  public void testEtsi239() throws CloneNotSupportedException, TallennaException {    // Kysely: 239
    Kysely kysely = new Kysely(); 
    Koehenkilo kissa6 = new Koehenkilo(); kissa6.rekisteroi(); 
    kissa6.setNimi("k100"); 
    kissa6.setSukupuoli("m"); 
    kissa6.setIkaryhma("10-15"); 
    kysely.lisaa(kissa6); 
    Collection<Koehenkilo> loytyneet = kysely.etsi("*100*", 1); 
    assertEquals("From: Kysely line: 248", 1, loytyneet.size()); 
    Iterator<Koehenkilo> it = loytyneet.iterator(); 
    assertEquals("From: Kysely line: 250", true, it.next() == kissa6); 
    assertEquals("From: Kysely line: 251", false, it.hasNext()); 
  } // Generated by ComTest END
}