package kysely.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kysely.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.12.14 21:32:14 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KysymysTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi80 */
  @Test
  public void testRekisteroi80() {    // Kysymys: 80
    Kysymys k1 = new Kysymys(); 
    assertEquals("From: Kysymys line: 82", 0, k1.getId()); 
    k1.rekisteroi(); 
    Kysymys k2 = new Kysymys(); 
    k2.rekisteroi(); 
    int n1 = k1.getId(); 
    int n2 = k2.getId(); 
    assertEquals("From: Kysymys line: 88", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString246 */
  @Test
  public void testToString246() {    // Kysymys: 246
    Kysymys kys = new Kysymys(); 
    kys.parse("1|2|kissako|a) joo b) ei|a) joo"); 
    String tulos = kys.toString(); 
    assertEquals("From: Kysymys line: 250", "1|2|kissako|a) joo b) ei|a) joo", tulos); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse269 */
  @Test
  public void testParse269() {    // Kysymys: 269
    Kysymys kys = new Kysymys(); 
    kys.parse("1|2|kissako|a) joo b) ei|a) joo"); 
    assertEquals("From: Kysymys line: 272", "kissako", kys.anna(2)); 
    assertEquals("From: Kysymys line: 273", "a) joo", kys.anna(4)); 
  } // Generated by ComTest END
}