package kysely.test;
// Generated by ComTest BEGIN
import java.io.*;
import java.util.*;
import java.io.File;
import java.util.Iterator;
import static org.junit.Assert.*;
import org.junit.*;
import kysely.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.07.22 13:19:00 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KysymyksetTest {

  // Generated by ComTest BEGIN  // Kysymykset: 36

  private Kysymykset kyssarit; 
  private String tiedNimi; 
  private File ftied; 

  @Before
  public void alusta() throws TallennaException {
     tiedNimi = "testikysely"; 
     ftied = new File(tiedNimi+".db"); 
     ftied.delete(); 
     kyssarit = new Kysymykset(tiedNimi); 
  }

  @After
  public void siivoa() {
     ftied.delete(); 
  }
  // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testAnnaKysymykset125 
   * @throws TallennaException when error
   */
  @Test
  public void testAnnaKysymykset125() throws TallennaException {    // Kysymykset: 125
    Kysymys pitsi21 = new Kysymys(2); pitsi21.taytaEsimKysymysTiedot(2); kyssarit.lisaa(pitsi21); 
    Kysymys pitsi11 = new Kysymys(1); pitsi11.taytaEsimKysymysTiedot(1); kyssarit.lisaa(pitsi11); 
    Kysymys pitsi22 = new Kysymys(2); pitsi22.taytaEsimKysymysTiedot(2); kyssarit.lisaa(pitsi22); 
    Kysymys pitsi12 = new Kysymys(1); pitsi12.taytaEsimKysymysTiedot(1); kyssarit.lisaa(pitsi12); 
    Kysymys pitsi23 = new Kysymys(2); pitsi23.taytaEsimKysymysTiedot(2); kyssarit.lisaa(pitsi23); 
    Kysymys pitsi51 = new Kysymys(5); pitsi51.taytaEsimKysymysTiedot(5); kyssarit.lisaa(pitsi51); 
    List<Kysymys> loytyneet; 
    loytyneet = kyssarit.annaKysymykset(3); 
    assertEquals("From: Kysymykset line: 138", 0, loytyneet.size()); 
    loytyneet = kyssarit.annaKysymykset(1); 
    assertEquals("From: Kysymykset line: 140", 2, loytyneet.size()); 
    assertEquals("From: Kysymykset line: 142", pitsi11, loytyneet.get(0)); 
    assertEquals("From: Kysymykset line: 143", pitsi12, loytyneet.get(1)); 
    loytyneet = kyssarit.annaKysymykset(5); 
    assertEquals("From: Kysymykset line: 146", 1, loytyneet.size()); 
    assertEquals("From: Kysymykset line: 147", pitsi51, loytyneet.get(0)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testKorvaaTaiLisaa203 
   * @throws TallennaException when error
   */
  @Test
  public void testKorvaaTaiLisaa203() throws TallennaException {    // Kysymykset: 203
    Kysymykset kyssarit = new Kysymykset(); 
    Kysymys kys1 = new Kysymys(1); kyssarit.lisaa(kys1); 
    Kysymys kys2 = new Kysymys(2); kyssarit.lisaa(kys2); 
    Kysymys kys3 = new Kysymys(1); kyssarit.lisaa(kys3); 
    Kysymys kys4 = new Kysymys(2); kyssarit.lisaa(kys4); 
    List<Kysymys> loydetyt; 
    loydetyt = kyssarit.annaKysymykset(6); 
    assertEquals("From: Kysymykset line: 214", 0, loydetyt.size()); 
    loydetyt = kyssarit.annaKysymykset(1); 
    assertEquals("From: Kysymykset line: 216", 2, loydetyt.size()); 
    assertEquals("From: Kysymykset line: 217", true, loydetyt.get(0) == kys1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta324 
   * @throws TallennaException when error
   */
  @Test
  public void testLueTiedostosta324() throws TallennaException {    // Kysymykset: 324
    Kysymykset kyssarit = new Kysymykset(); 
    Kysymys kys1 = new Kysymys(); kys1.taytaEsimKysymysTiedot(1); 
    Kysymys kys2 = new Kysymys(); kys2.taytaEsimKysymysTiedot(2); 
    Kysymys kys3 = new Kysymys(); kys3.taytaEsimKysymysTiedot(3); 
    kyssarit.lueTiedostosta(); 
    kyssarit.lisaa(kys1); 
    kyssarit.lisaa(kys2); 
    kyssarit.lisaa(kys3); 
    kyssarit.tallenna(); 
    kyssarit = new Kysymykset(); 
    kyssarit.lueTiedostosta(); 
    Iterator<Kysymys> i = kyssarit.iterator(); 
    assertEquals("From: Kysymykset line: 340", kys1.toString(), i.next().toString()); 
    assertEquals("From: Kysymykset line: 341", kys2.toString(), i.next().toString()); 
    assertEquals("From: Kysymykset line: 342", kys3.toString(), i.next().toString()); 
  } // Generated by ComTest END
}