package kysely.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import java.util.*;
import kysely.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.11.03 12:11:51 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KysymyksetTest {



  // Generated by ComTest BEGIN
  /** testAnnaKysymykset44 */
  @Test
  public void testAnnaKysymykset44() {    // Kysymykset: 44
    Kysymykset kyssarit = new Kysymykset(); 
    Kysymys kys1 = new Kysymys(1); kyssarit.lisaa(kys1); 
    Kysymys kys2 = new Kysymys(2); kyssarit.lisaa(kys2); 
    Kysymys kys3 = new Kysymys(1); kyssarit.lisaa(kys3); 
    Kysymys kys4 = new Kysymys(2); kyssarit.lisaa(kys4); 
    List<Kysymys> loydetyt; 
    loydetyt = kyssarit.annaKysymykset(6); 
    assertEquals("From: Kysymykset line: 54", 0, loydetyt.size()); 
    loydetyt = kyssarit.annaKysymykset(1); 
    assertEquals("From: Kysymykset line: 56", 2, loydetyt.size()); 
    assertEquals("From: Kysymykset line: 57", true, loydetyt.get(0) == kys1); 
  } // Generated by ComTest END
}