package kysely.test;
// Generated by ComTest BEGIN
import java.io.File;
import java.util.Iterator;
import static org.junit.Assert.*;
import org.junit.*;
import java.util.*;
import kysely.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.12.14 16:42:57 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KysymyksetTest {



  // Generated by ComTest BEGIN
  /** 
   * testAnnaKysymykset58 
   * @throws TallennaException when error
   */
  @Test
  public void testAnnaKysymykset58() throws TallennaException {    // Kysymykset: 58
    Kysymykset kyssarit = new Kysymykset(); 
    Kysymys kys1 = new Kysymys(1); kyssarit.lisaa(kys1); 
    Kysymys kys2 = new Kysymys(2); kyssarit.lisaa(kys2); 
    Kysymys kys3 = new Kysymys(1); kyssarit.lisaa(kys3); 
    Kysymys kys4 = new Kysymys(2); kyssarit.lisaa(kys4); 
    List<Kysymys> loydetyt; 
    loydetyt = kyssarit.annaKysymykset(6); 
    assertEquals("From: Kysymykset line: 69", 0, loydetyt.size()); 
    loydetyt = kyssarit.annaKysymykset(1); 
    assertEquals("From: Kysymykset line: 71", 2, loydetyt.size()); 
    assertEquals("From: Kysymykset line: 72", true, loydetyt.get(0) == kys1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta147 
   * @throws TallennaException when error
   */
  @Test
  public void testLueTiedostosta147() throws TallennaException {    // Kysymykset: 147
    Kysymykset kyssarit = new Kysymykset(); 
    Kysymys kys1 = new Kysymys(); kys1.taytaEsimKysymysTiedot(1); 
    Kysymys kys2 = new Kysymys(); kys2.taytaEsimKysymysTiedot(2); 
    Kysymys kys3 = new Kysymys(); kys3.taytaEsimKysymysTiedot(3); 
    kyssarit.lueTiedostosta(); 
    kyssarit.lisaa(kys1); 
    kyssarit.lisaa(kys2); 
    kyssarit.lisaa(kys3); 
    kyssarit.tallenna(); 
    kyssarit = new Kysymykset(); 
    kyssarit.lueTiedostosta(); 
    Iterator<Kysymys> i = kyssarit.iterator(); 
    assertEquals("From: Kysymykset line: 163", kys1.toString(), i.next().toString()); 
    assertEquals("From: Kysymykset line: 164", kys2.toString(), i.next().toString()); 
    assertEquals("From: Kysymykset line: 165", kys3.toString(), i.next().toString()); 
  } // Generated by ComTest END
}