package kysely.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kysely.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.07.22 13:17:19 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KysymysTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi188 */
  @Test
  public void testRekisteroi188() {    // Kysymys: 188
    Kysymys k1 = new Kysymys(); 
    assertEquals("From: Kysymys line: 190", 0, k1.getId()); 
    k1.rekisteroi(); 
    Kysymys k2 = new Kysymys(); 
    k2.rekisteroi(); 
    int n1 = k1.getId(); 
    int n2 = k2.getId(); 
    assertEquals("From: Kysymys line: 196", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString354 */
  @Test
  public void testToString354() {    // Kysymys: 354
    Kysymys kys = new Kysymys(); 
    kys.parse("1|2|kissako|a) joo b) ei|a) joo"); 
    String tulos = kys.toString(); 
    assertEquals("From: Kysymys line: 358", "1|2|kissako|a) joo b) ei|a) joo", tulos); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse377 */
  @Test
  public void testParse377() {    // Kysymys: 377
    Kysymys kys = new Kysymys(); 
    kys.parse("1|2|kissako|a) joo b) ei|a) joo"); 
    assertEquals("From: Kysymys line: 380", "kissako", kys.anna(2)); 
    assertEquals("From: Kysymys line: 381", "a) joo", kys.anna(4)); 
  } // Generated by ComTest END
}