package kysely.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kysely.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.11.10 17:02:48 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KysymysTest {


  // Generated by ComTest BEGIN
  /** testRekisteroi75 */
  @Test
  public void testRekisteroi75() {    // Kysymys: 75
    Kysymys k1 = new Kysymys(); 
    assertEquals("From: Kysymys line: 77", 0, k1.getId()); 
    k1.rekisteroi(); 
    Kysymys k2 = new Kysymys(); 
    k2.rekisteroi(); 
    int n1 = k1.getId(); 
    int n2 = k2.getId(); 
    assertEquals("From: Kysymys line: 83", n2-1, n1); 
  } // Generated by ComTest END
}