package kysely.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import java.util.*;
import kysely.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.11.10 16:53:23 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class VastauksetTest {


  // Generated by ComTest BEGIN
  /** testAnnaVastaukset41 */
  @Test
  public void testAnnaVastaukset41() {    // Vastaukset: 41
    Kysymykset kyssarit = new Kysymykset(); 
    Kysymys kys1 = new Kysymys(1); kyssarit.lisaa(kys1); 
    Kysymys kys2 = new Kysymys(2); kyssarit.lisaa(kys2); 
    Kysymys kys3 = new Kysymys(1); kyssarit.lisaa(kys3); 
    Kysymys kys4 = new Kysymys(2); kyssarit.lisaa(kys4); 
    List<Kysymys> loydetyt; 
    loydetyt = kyssarit.annaKysymykset(6); 
    assertEquals("From: Vastaukset line: 51", 0, loydetyt.size()); 
    loydetyt = kyssarit.annaKysymykset(1); 
    assertEquals("From: Vastaukset line: 53", 2, loydetyt.size()); 
    assertEquals("From: Vastaukset line: 54", true, loydetyt.get(0) == kys1); 
  } // Generated by ComTest END
}