package kysely.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kysely.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.11.10 16:55:42 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class VastausTest {


  // Generated by ComTest BEGIN
  /** testRekisteroi71 */
  @Test
  public void testRekisteroi71() {    // Vastaus: 71
    Vastaus v1 = new Vastaus(); 
    assertEquals("From: Vastaus line: 73", 0, v1.getId()); 
    v1.rekisteroi(); 
    Vastaus v2 = new Vastaus(); 
    v2.rekisteroi(); 
    int n1 = v1.getId(); 
    int n2 = v2.getId(); 
    assertEquals("From: Vastaus line: 79", n2-1, n1); 
  } // Generated by ComTest END
}