package kysely.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import java.util.*;
import kysely.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.11.10 16:53:23 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class VastauksetTest {


  // Generated by ComTest BEGIN
  /** testAnnaVastaukset41 */
  @Test
  public void testAnnaVastaukset41() {    // Vastaukset: 41
    Vastaukset vassarit = new Vastaukset(); 
    Vastaus vas1 = new Vastaus(1); vassarit.lisaa(vas1); 
    Vastaus vas2 = new Vastaus(2); vassarit.lisaa(vas2); 
    Vastaus vas3 = new Vastaus(1); vassarit.lisaa(vas3); 
    Vastaus vas4 = new Vastaus(2); vassarit.lisaa(vas4); 
    List<Vastaus> loydetyt; 
    loydetyt = vassarit.annaVastaukset(6); 
    assertEquals("From: Vastaukset line: 51", 0, loydetyt.size()); 
    loydetyt = vassarit.annaVastaukset(1); 
    assertEquals("From: Vastaukset line: 53", 2, loydetyt.size()); 
    assertEquals("From: Vastaukset line: 54", true, loydetyt.get(0) == vas1); 
  } // Generated by ComTest END
}